import { useState } from "react";
import { useOutletContext } from "react-router-dom";
import { BookOpen, LayoutDashboard, FlaskConical, BarChart2, BarChart3, Gauge, CalendarDays, CalendarPlus, MessageSquare, ListChecks, LineChart, ClipboardList, User, ChevronRight, Play } from "lucide-react";
import { Button } from "@/components/ui";

interface DocSection {
  id: string;
  icon: React.ElementType;
  title: string;
  subtitle: string;
  content: DocItem[];
}

interface DocItem {
  title: string;
  description: string;
  steps?: string[];
}

const SECTIONS: DocSection[] = [
  {
    id: "getting-started",
    icon: BookOpen,
    title: "Getting Started",
    subtitle: "Your first steps on the dashboard",
    content: [
      {
        title: "What is this dashboard?",
        description:
          "This is your Optimizers client dashboard — your central view of all A/B testing activity, ROI, and experiment results. Data is pulled from Convert.com and refreshed automatically every day at 8 AM and 8 PM Cairo time. You do not need to do anything to keep it current; simply check back and the numbers will be up to date.",
      },
      {
        title: "Navigating the dashboard",
        description: "Use the sidebar on the left to move between sections. Each icon takes you to a different part of the dashboard.",
        steps: [
          "A/B Testing Results → Your experiments, metrics, and charts",
          "GA4 Data View → Google Analytics 4 metrics for your experiments",
          "Page Speed → Site performance audits via Google PageSpeed Insights",
          "Timeline → Your project roadmap and phases",
          "Book a Meeting → Schedule time with our team",
          "Support → Chat directly with us",
          "Docs → This documentation page (you are here)",
          "Profile → Change your account password",
          "Audit Findings, Analytics Reports, and Project Tasks appear automatically once those features are enabled or connected for your account",
        ],
      },
      {
        title: "Re-launching the tutorial",
        description: "You can restart the full interactive walkthrough at any time by clicking the 'Launch Tutorial' button at the top of this page.",
      },
    ],
  },
  {
    id: "dashboard",
    icon: LayoutDashboard,
    title: "Dashboard",
    subtitle: "KPIs, ROI, charts, and recent experiments",
    content: [
      {
        title: "Date Range Filter",
        description:
          "All metrics on the dashboard respond to the date range you set. By default it shows your full engagement window. Narrow it to see performance in a specific period.",
        steps: [
          "Click the Start date input and pick a date",
          "Click the End date input and pick an end date",
          "All KPI cards, the ROI panel, and the chart update instantly",
          "Click 'Full Range' at any time to reset to the full period",
        ],
      },
      {
        title: "KPI Cards — Revenue, Purchases, Products Uplift",
        description:
          "The three cards at the top show the combined uplift from all experiments in your selected date range. These are the core headline numbers.",
        steps: [
          "Revenue Uplift: extra revenue generated by your experiments vs. the original variation",
          "Purchases Uplift: additional transactions attributed to your experiments",
          "Products Uplift: additional products sold across all experiments",
          "Adjust the date range to see how these numbers change over different periods",
        ],
      },
      {
        title: "Return on Investment (ROI) Panel",
        description:
          "The ROI panel shows how much value your experiments have generated relative to the cost of the Optimizers service.",
        steps: [
          "The progress bar moves right as your ROI grows",
          "Milestones show 25%, 50%, 75%, Breakeven, and post-breakeven multipliers",
          "Once the marker passes 'Breakeven', your experiments have paid for the service",
          "Below the bar: Service Investment, Revenue Uplift, Net Profit, and Current ROI multiplier",
        ],
      },
      {
        title: "Revenue Uplift Over Time Chart",
        description:
          "This chart shows daily revenue uplift across all your experiments. It helps you spot patterns, winning streaks, and the impact of specific tests.",
        steps: [
          "Hover over any date point to see the total revenue uplift for that day",
          "The side panel shows a breakdown of which experiments contributed",
          "Green areas = positive days, red areas = negative days",
          "Use the date range filter to zoom into any time window",
        ],
      },
      {
        title: "Exclude Revenue Losses",
        description:
          "This toggle removes experiments with negative revenue uplift from all totals. Use it to see your 'best case' performance.",
        steps: [
          "Tick the checkbox labeled 'Exclude revenue losses from totals'",
          "All KPI cards and the chart update immediately",
          "The count of excluded experiments is shown next to the checkbox",
          "Untick to restore all experiments to the totals",
        ],
      },
      {
        title: "Rate Metrics — RPV, CVR, AOV",
        description:
          "These metrics show the impact on Revenue Per Visitor, Conversion Rate, and Average Order Value across your experiments.",
        steps: [
          "Click 'Average' to see the typical impact per experiment",
          "Click 'Sum' to see the total combined impact across all experiments",
          "RPV = Revenue Per Visitor, CVR = Conversion Rate, AOV = Average Order Value",
        ],
      },
      {
        title: "Recent Experiments",
        description:
          "The table at the bottom of the dashboard lists your 5 most recently started experiments with their key metric uplifts.",
        steps: [
          "Green numbers = positive uplift versus the original variation",
          "Red numbers = negative uplift",
          "Click any experiment name to open the full detail page",
          "Go to the Experiments section to see all experiments",
        ],
      },
    ],
  },
  {
    id: "experiments",
    icon: FlaskConical,
    title: "Experiments",
    subtitle: "Your full experiment list with search, sort, and detail views",
    content: [
      {
        title: "Viewing all experiments",
        description: "The Experiments page shows every experiment with full metric columns. Click 'A/B Testing Results' in the sidebar, then 'Open view' on the Experiments card.",
        steps: [
          "Click 'A/B Testing Results' in the left sidebar",
          "Click the 'Experiments' card",
          "The full list appears with all 6 metric columns",
        ],
      },
      {
        title: "Searching experiments",
        description: "The search box filters the experiments list instantly as you type.",
        steps: [
          "Click the search box at the top left of the experiments table",
          "Type any part of the experiment name",
          "The list filters instantly as you type",
          "Clear the box to show all experiments again",
        ],
      },
      {
        title: "Sorting experiments",
        description: "Reorder the list by any metric to surface the best or worst performing experiments.",
        steps: [
          "Click the sort dropdown (top right of the experiments area)",
          "Choose from Revenue, RPV, Purchases, Products, CVR, AOV, Name, or Status",
          "The list reorders immediately with the highest value at the top",
        ],
      },
      {
        title: "Understanding experiment rows",
        description: "Each row shows the status of an experiment and its uplift across all 6 metrics.",
        steps: [
          "The status badge (Running, Completed, Paused) shows current state",
          "Green metric values = positive uplift, red = negative",
          "'--' means no data is available for that metric yet",
          "Click 'View detail' to open the full experiment breakdown",
        ],
      },
      {
        title: "Hiding experiments from your dashboard",
        description: "You can hide specific experiments so they don't affect your totals or appear in charts.",
        steps: [
          "Find the experiment in the list",
          "Click the eye icon (👁) on that row",
          "The experiment is faded and marked 'Hidden from dashboard'",
          "Click the eye icon again to restore it",
          "Hidden experiments are excluded from all KPI totals and the chart",
        ],
      },
      {
        title: "Experiment detail page",
        description: "Click 'View detail' on any experiment to see the complete per-variation breakdown.",
        steps: [
          "The top section shows experiment status, dates, and ID",
          "An admin note may appear in amber if your team has added context",
          "The Metric Uplift table shows original vs. best variation for all 6 metrics",
          "The Variation Metrics table shows raw numbers for every variation",
          "The Goals Breakdown shows conversion data per goal",
          "You can hide/show the experiment using the button at the top right",
        ],
      },
    ],
  },
  {
    id: "abtesting",
    icon: BarChart2,
    title: "A/B Testing Hub",
    subtitle: "Navigate between dashboard and experiment views",
    content: [
      {
        title: "Choosing a view",
        description: "The A/B Testing Results hub gives you two routes into your data.",
        steps: [
          "Click 'A/B Testing Results' in the left sidebar",
          "'Dashboard View' takes you to the main dashboard with aggregated KPIs and charts",
          "'Experiments' takes you to the full experiment list",
          "Both are accessible directly from the sidebar at any time",
        ],
      },
    ],
  },
  {
    id: "ga4",
    icon: BarChart3,
    title: "GA4 Data View",
    subtitle: "Google Analytics 4 metrics for your experiments",
    content: [
      {
        title: "Choosing a view",
        description:
          "GA4 Data View gives you two routes into your Google Analytics 4 experiment data, sourced from GA4 audiences named 'Convert {experimentId}-{variationId}'. This is separate from the Convert-based Experiments data documented above.",
        steps: [
          "Click 'GA4 Data View' in the left sidebar",
          "'Dashboard View' shows aggregated KPIs across all GA4-tracked experiments",
          "'Experiments View' shows a per-experiment original vs. variation breakdown",
          "Both views are always available in the sidebar",
        ],
      },
      {
        title: "GA4 Dashboard View",
        description: "Summary KPIs aggregated across every GA4-tracked experiment, comparing the original to the variation.",
        steps: [
          "Revenue, Purchases, and Products Uplift cards summarize impact across all GA4 experiments",
          "Average CVR and RPV Uplift show rate-based impact",
          "Scroll down to see the per-experiment list beneath the KPI cards",
        ],
      },
      {
        title: "GA4 Experiments View",
        description: "A per-experiment breakdown of original vs. variation audiences, drawn directly from GA4.",
        steps: [
          "Open 'Experiments View' from the GA4 Data View chooser",
          "Each row shows the original and variation audience side by side",
          "Use this to cross-check GA4 numbers against your Convert experiment results",
        ],
      },
    ],
  },
  {
    id: "page-speed",
    icon: Gauge,
    title: "Page Speed",
    subtitle: "Site performance audits via Google PageSpeed Insights",
    content: [
      {
        title: "Running a report",
        description: "Page Speed crawls your site and runs Google PageSpeed Insights against every page.",
        steps: [
          "Click 'Page Speed' in the left sidebar",
          "Toggle between Mobile and Desktop strategy",
          "Pages are pulled automatically from your sitemap, or you can add URLs manually",
          "Click 'Run Report' to start — a progress bar tracks the background job",
          "Click 'Stop Report' at any time to cancel; partial results are kept",
        ],
      },
      {
        title: "Reading your scores",
        description: "Each run produces four Lighthouse scores plus detailed Core Web Vitals.",
        steps: [
          "Performance, Accessibility, SEO, and Best Practices are shown as gauges",
          "Core Web Vitals (LCP, FCP, CLS, TBT, SI, INP) show detailed loading and interactivity metrics",
          "Expand the full audit metrics panel for every Lighthouse check",
          "PSI screenshots and load filmstrips show how the page rendered over time",
        ],
      },
      {
        title: "Page-by-page table",
        description: "Every crawled page gets its own row with its own scores.",
        steps: [
          "Use the search box to filter by URL",
          "Click a column header to sort by any score or metric",
          "Click a row's PSI link to open the official PageSpeed Insights report",
        ],
      },
      {
        title: "Past Runs & comparing reports",
        description: "Every report you run is saved so you can track performance over time.",
        steps: [
          "Scroll down to 'Past Runs' to see every previous report with its date, strategy, and average scores",
          "Once you have 2 or more runs, click 'Compare Runs'",
          "Select two or more runs to see side-by-side bar charts for every metric",
          "Expand the per-page breakdown table to compare individual pages across runs",
        ],
      },
    ],
  },
  {
    id: "timeline",
    icon: CalendarDays,
    title: "Timeline",
    subtitle: "Your project roadmap, synced live from ClickUp",
    content: [
      {
        title: "Reading your timeline",
        description:
          "The Timeline shows a live Gantt chart of your project, auto-generated from our ClickUp task tracker.",
        steps: [
          "Click 'Timeline' in the left sidebar",
          "Each bar represents a synced ClickUp task, positioned by its schedule",
          "Tasks show their status (Open, In Progress, Complete)",
          "The chart updates automatically as our team makes progress — no manual updates needed",
        ],
      },
    ],
  },
  {
    id: "meetings",
    icon: CalendarPlus,
    title: "Book a Meeting",
    subtitle: "Schedule time with the Optimizers team",
    content: [
      {
        title: "Business Meeting",
        description: "Use this for strategy, commercial discussions, priorities, and planning.",
        steps: [
          "Click 'Book a Meeting' in the left sidebar",
          "Click the 'Business Meeting' card",
          "Calendly opens in a new tab",
          "Choose a date and time that works for you",
          "Fill in your details and confirm the booking",
          "You'll receive a calendar invite by email",
        ],
      },
      {
        title: "Technical Meeting",
        description: "Use this for implementation, tracking, integrations, or deeper product questions.",
        steps: [
          "Click 'Book a Meeting' in the left sidebar",
          "Click the 'Technical Meeting' card",
          "This connects you with our technical team via Calendly",
          "Choose a time and confirm the booking",
        ],
      },
    ],
  },
  {
    id: "support",
    icon: MessageSquare,
    title: "Support",
    subtitle: "Chat directly with our team",
    content: [
      {
        title: "Sending a message",
        description: "You have two ways to reach us: the Support page and the floating chat bubble available on every page.",
        steps: [
          "Click 'Support' in the left sidebar, or click the chat bubble (bottom right corner)",
          "Type your message in the text box",
          "Press Enter or click the Send button",
          "Our team receives it immediately and will respond as soon as possible",
          "All previous messages are saved so you can see the full conversation history",
        ],
      },
      {
        title: "Using the floating chat",
        description: "The floating chat bubble is available on every page — you never need to navigate away to send a message.",
        steps: [
          "Look for the green chat bubble in the bottom right corner",
          "Click it to open the chat panel",
          "Type and send your message",
          "Click the bubble again (or the X) to close it",
          "An unread badge appears if our team has replied",
        ],
      },
    ],
  },
  {
    id: "audit-findings",
    icon: ListChecks,
    title: "Audit Findings",
    subtitle: "Track fixes from your tracking & analytics audit",
    content: [
      {
        title: "Understanding your findings",
        description:
          "This section is only visible if your account has audit tracking enabled — it may not appear in your sidebar. KPI cards summarize Total findings, Fixed, and Completion %. Select any finding from the list to see its full detail.",
        steps: [
          "Click 'Audit Findings' in the left sidebar (if visible)",
          "Review the Total / Fixed / Completion % cards at the top",
          "Click any finding in the list to open its detail view",
        ],
      },
      {
        title: "Filtering findings",
        description: "Narrow the list down using the filter controls above it.",
        steps: [
          "Use the filter controls to narrow findings by severity, tool, or status",
          "Clear the filters to see the full list again",
        ],
      },
      {
        title: "Plain-English vs. technical view",
        description: "Each finding can be read in simplified business language or in full technical detail.",
        steps: [
          "Open any finding from the list",
          "Toggle between plain-English and technical wording",
          "Tick 'Show full details' to reveal the fix, verification steps, and documentation links",
        ],
      },
    ],
  },
  {
    id: "analytics-reports",
    icon: LineChart,
    title: "Analytics Reports",
    subtitle: "Custom GA4 reports built for your account",
    content: [
      {
        title: "Viewing your reports",
        description:
          "This section is only visible if your account has analytics reports enabled — it may not appear in your sidebar. It's a read-only grid of custom GA4 reports built for you.",
        steps: [
          "Click 'Analytics Reports' in the left sidebar (if visible)",
          "Reports are grouped into sections; click any report card to open it",
          "The full report view shows charts, funnels, and key numbers",
          "If no reports have been shared with you yet, you'll see an empty state",
        ],
      },
    ],
  },
  {
    id: "tasks",
    icon: ClipboardList,
    title: "Project Tasks",
    subtitle: "Your ClickUp tasks, synced automatically",
    content: [
      {
        title: "Browsing your tasks",
        description:
          "This section is only visible once your ClickUp workspace is connected — it may not appear in your sidebar. Tasks are grouped by ClickUp list and fully read-only.",
        steps: [
          "Click 'Project Tasks' in the left sidebar (if visible)",
          "Click a list header to expand or collapse it",
          "Subtasks are nested underneath their parent task",
          "Each task shows a status badge, due date, and assignees",
        ],
      },
      {
        title: "Task detail",
        description: "Click any task to see its full description, assignees, and dates.",
        steps: [
          "Click any task row to open its detail view",
          "Review the description, assignees, and start/due dates",
          "Close the detail view with the X, Escape, or by clicking outside it",
        ],
      },
    ],
  },
  {
    id: "profile",
    icon: User,
    title: "Profile",
    subtitle: "Manage your account settings",
    content: [
      {
        title: "Changing your password",
        description: "You can update your login password from the Profile page at any time.",
        steps: [
          "Click your avatar or 'Profile' at the bottom of the sidebar",
          "Enter your new password (minimum 8 characters)",
          "Enter it again to confirm",
          "Click 'Update Password'",
          "You will need to use the new password next time you log in",
        ],
      },
    ],
  },
];

export function DocsPage() {
  const { startTutorial: onLaunchTutorial } = useOutletContext<{ startTutorial: () => void }>();
  const [activeSection, setActiveSection] = useState(SECTIONS[0].id);
  const section = SECTIONS.find((s) => s.id === activeSection) ?? SECTIONS[0];

  return (
    <div className="flex min-h-screen">
      {/* Sidebar TOC */}
      <aside className="w-64 shrink-0 border-r border-ink/10 bg-white flex flex-col">
        <div className="px-5 py-6 border-b border-ink/10">
          <p className="text-[10px] font-bold uppercase tracking-widest text-ink/40 mb-3">Documentation</p>
          <Button className="w-full" onClick={onLaunchTutorial}>
            <Play className="mr-2 h-4 w-4" />
            Launch Tutorial
          </Button>
        </div>
        <nav className="flex-1 px-3 py-4 space-y-0.5 overflow-y-auto">
          {SECTIONS.map(({ id, icon: Icon, title }) => (
            <button
              key={id}
              onClick={() => setActiveSection(id)}
              className={`flex items-center gap-3 w-full px-3 py-2.5 rounded-xl text-sm font-medium transition-all text-left ${
                activeSection === id
                  ? "bg-brand-500/10 text-ink"
                  : "text-ink/50 hover:bg-ink/5 hover:text-ink"
              }`}
            >
              <Icon className="h-4 w-4 shrink-0" />
              {title}
            </button>
          ))}
        </nav>
      </aside>

      {/* Content */}
      <main className="flex-1 overflow-y-auto">
        <div className="max-w-3xl px-10 py-10">
          {/* Section header */}
          <div className="mb-8">
            <div className="flex items-center gap-3 mb-2">
              <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-brand-100 text-brand-700">
                <section.icon className="h-5 w-5" />
              </div>
              <h1 className="text-2xl font-bold text-ink">{section.title}</h1>
            </div>
            <p className="text-sm text-ink/50">{section.subtitle}</p>
          </div>

          {/* Items */}
          <div className="space-y-8">
            {section.content.map((item, i) => (
              <div key={i} className="rounded-2xl border border-ink/8 bg-white p-6">
                <h2 className="font-semibold text-ink text-base mb-2">{item.title}</h2>
                <p className="text-sm text-ink/60 leading-relaxed mb-4">{item.description}</p>
                {item.steps && (
                  <ol className="space-y-2">
                    {item.steps.map((step, j) => (
                      <li key={j} className="flex items-start gap-3 text-sm">
                        <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-brand-100 text-brand-700 text-[10px] font-bold mt-0.5">
                          {j + 1}
                        </span>
                        <span className="text-ink/70 leading-relaxed">{step}</span>
                      </li>
                    ))}
                  </ol>
                )}
              </div>
            ))}
          </div>

          {/* Next section hint */}
          {SECTIONS.findIndex((s) => s.id === activeSection) < SECTIONS.length - 1 && (
            <button
              onClick={() => {
                const idx = SECTIONS.findIndex((s) => s.id === activeSection);
                setActiveSection(SECTIONS[idx + 1].id);
              }}
              className="mt-8 flex items-center gap-2 text-sm text-ink/40 hover:text-ink transition-colors"
            >
              Next: {SECTIONS[SECTIONS.findIndex((s) => s.id === activeSection) + 1].title}
              <ChevronRight className="h-4 w-4" />
            </button>
          )}
        </div>
      </main>
    </div>
  );
}
